---
- name: Create docker volume of nexus
  docker_volume:
    name: "{{volume_prefix}}nexus"

- name: create nexus container
  docker_container:
    name: "{{ nexus.name }}"
    image: sonatype/nexus3:3.20.1
    restart_policy: always
    ports:
    - "{{ nexus.port }}:8081"
    volumes:
    - "{{volume_prefix}}nexus:/nexus-data"