concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Linux Builder (Docker) for epm group"
  url = "http://172.16.0.119:8000/"
  token = "UtcX7z9Rchs7ZjqAyx1N"
  executor = "docker"
  environment = ["EPM_CI_VIRTUAL_ENVIRONMENT_DIR=/home/conan/@venv"]
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "must-be-specified-docker"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/home/epm/venv/epm-oss:/home/conan/@venv"]
    pull_policy = "if-not-present"
    shm_size = 0

[[runners]]
  name = "Linux raw docker executor"
  url = "http://172.16.0.119:8000/"
  token = "jx2U5i9juuhP1Va5EDZ_"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "ubuntu:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    pull_policy = "if-not-present"
    shm_size = 0

[[runners]]
  name = "Linux conan package deployer for epm group"
  url = "http://172.16.0.119:8000/"
  token = "UR6rshyV9kpG16S2YL8a"
  executor = "docker"
  environment = ["EPM_CI_VIRTUAL_ENVIRONMENT_DIR=/home/conan/@venv"]
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "epmkit/gcc5:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/home/epm/venv/epm-oss.deployer:/home/conan/@venv"]
    pull_policy = "if-not-present"
    shm_size = 0

[[runners]]
  name = "Linux Builder (Docker) for NVR group"
  url = "http://172.16.0.119:8000/"
  token = "MyYq7A7itsdu4iYuzaiC"
  executor = "docker"
  environment = ["EPM_CI_VIRTUAL_ENVIRONMENT_DIR=/home/conan/@venv"]
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "[PLEASE SPECIFY BUILD IMAGE]"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/home/epm/venv/nvr:/home/conan/@venv"]
    pull_policy = "if-not-present"
    shm_size = 0

[[runners]]
  name = "Conan package deployer (linux) for NVR group"
  url = "http://172.16.0.119:8000/"
  token = "1vNMMUA9pDWReN1XZbX2"
  executor = "docker"
  environment = ["EPM_CI_VIRTUAL_ENVIRONMENT_DIR=/home/conan/@venv"]
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "epmkit/gcc5"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/home/epm/venv/nvr.deployer:/home/conan/@venv"]
    pull_policy = "if-not-present"
    shm_size = 0

[[runners]]
  name = "HiSiv300 runner"
  url = "http://172.16.0.119:8000/"
  token = "LfzAxXU5qh4J6zyxz1We"
  executor = "custom"
  builds_dir = "/tmp/_ci/__builds"
  cache_dir = "/tmp/_ci/__cache"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.custom]
    
    config_exec = "/home/epm/_ci/config.sh"
    config_args = ["172.16.192.242"]
    config_exec_timeout = 200

    prepare_exec = "/home/epm/_ci/prepare.sh"
    prepare_args = []
    prepare_exec_timeout = 200

    run_exec = "/home/epm/_ci/run.sh"
    run_args = ["172.16.192.242", "172.16.192.169"]

    cleanup_exec = "/home/epm/_ci/cleanup.sh"
    cleanup_args = []
    cleanup_exec_timeout = 200

    graceful_kill_timeout = 200
    force_kill_timeout = 200    
