
- name: clone epm git
  command: git clone 
- name: Get known docker image (debug)
  command: echo In dev enviroment
  register: result

- name: show exec infomation
  debug:
    var: result