#!/bin/bash
set -e
_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd ${_DIR}/..
[ ! -d .epm ] && mkdir -p .epm
sudo rm -f .epm/epm.tar.gz 
git archive --format=tar.gz --output .epm/epm.tar.gz HEAD
echo sudo -E ./docker/main.py $*
# https://registry.hub.docker.com/v1/repositories/conanio/gcc7-armv8/tags
sudo -E ./docker/main.py --build $*
