---
- name: Create docker volume of artifactory
  docker_volume:
    name: "{{volume_prefix}}artifactory"
  become: yes

- name: create artifactory container
  docker_container:
    name: "{{ artifactory.name }}"
#    image: docker.bintray.io/jfrog/artifactory-cpp-ce:6.17.0
    image: docker.bintray.io/jfrog/artifactory-cpp-ce:7.3.2
    restart_policy: always
    ports:
    - "{{ artifactory.port }}:8081"
    volumes:
    - "{{volume_prefix}}artifactory7:/var/opt/jfrog/artifactory"
  become: yes

        