---
- name: Create docker volume of gitlab
  docker_volume:
    name: "{{volume_prefix}}gitlab"

- name: Create config directory of gitlab
  file: path={{ conf_dir }}/gitlab state=directory

- name: Generate config file of gitlab
  template: "src=gitlab/{{ item }}.j2 dest={{ conf_dir }}/gitlab/{{ item }}"
  with_items:
    - gitlab.rb
    - sshd_config

- name: create gitlab container
  docker_container:
    name: "{{ gitlab.name }}"
    image: gitlab/gitlab-ce:12.7.6-ce.0 
    restart_policy: always
    ports:
    - "{{ gitlab.http_port }}:{{ gitlab.http_port }}"
    - "{{ gitlab.ssh_port }}:{{ gitlab.ssh_port }}"
    volumes:
    - "{{ conf_dir }}/gitlab/sshd_config:/assets/sshd_config"
    - "{{ conf_dir }}/gitlab/gitlab.rb:/etc/gitlab/gitlab.rb"
    - "{{volume_prefix}}gitlab:/var/opt/gitlab"
