---
- name: Create docker volume
  docker_volume:
    name: "{{volume_prefix}}registry"
  register: output

- name: Create config directory
  file: path={{ conf_dir }}/registry state=directory

- name: Generate config file
  template: src=registry/config.yml.j2 dest={{ conf_dir }}/registry/config.yml

#- name: Get registry conatianer information
#  docker_container_info:
#    name: "{{ registry.name }}"
#  register: result
#
#- name: Remove registry conatianer
#  docker_container:
#    name: "{{ registry.name }}"
#    state: absent
#  when: result.exists
  
- name: create registry container
  docker_container:
    name: "{{ registry.name }}"
    image: registry:2.7.1
    restart_policy: always
    ports:
      - "{{ registry.port }}:5000"
    volumes:
      - "{{ conf_dir }}/registry/config.yml:/etc/docker/registry/config.yml"
      - "{{volume_prefix}}registry:/var/lib/registry"
#    volumes_from:
#      - "{{volume_prefix}}registry:"
  register: output

- debug:
    var: output    