---
- name: Remove a directory if it exist
  file:
    path: ./tmpdir/epm
    state: absent

- name: Create a directory if it does not exist
  file:
    path: ./tmpdir
    state: directory
    mode: '0755'
    
- name: clone epm repository
  command: git clone {{ epm.url }} -b {{ epm.branch }}
  args:
    chdir: ./tmpdir

- name: Copy file with owner and permissions
  copy:
    src: docker.yml
    dest: docker.yml
    mode: '0644'
    
- name: create epm docker images
  command: python3 tmpdir/epm/tools/mkdocker.py {{item}} -c docker.yml -B --version latest --root-dir tmpdir/epm
  with_items:
    - gcc5
    - gcc5-x86
#  args:
#    chdir: ./tmpdir/epm
  register: output

- debug:
    var: output