---
- name: Create config directory of ngnix
  file: path={{ conf_dir }}/nginx/{{ item }} state=directory
  with_items:
    - conf.d

- name: Create storage direcatory
  file: path={{ storage_dir }} state=directory mode=0755

  
- name: Copy config file
  template: src=nginx/{{item.src}} dest={{ conf_dir }}/nginx/{{item.dest}}
  with_items:
    - { src: 'nginx.conf.j2' , dest: 'nginx.conf' }
    - { src: 'conf.d/default.conf.j2' , dest: 'conf.d/default.conf' }

- name: create docker nginx container
  docker_container:
    name: "{{ nginx.name }}"
    image: nginx:1.17.8
    restart_policy: always
    ports:
      - "{{ nginx.port }}:80"
    volumes:
      - "{{ conf_dir }}/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "{{ conf_dir }}/nginx/conf.d:/etc/nginx/conf.d"
      - "{{ storage_dir }}:/storage"
