builder:
  172.16.192.169:
    id: 19
    tags: &id001
    - builder
    - docker-executor
    token: 2Z8BNMujs6yNWK5S1DqZ
  172.16.192.241:
    id: 20
    tags: *id001
    token: tCKoy87FUGFkiH_wv2pu
conan.deployer:
  172.16.192.169:
    id: 23
    tags: &id002
    - conan.deployer
    token: sL3519CY995k6BBY_aqP
  172.16.192.241:
    id: 24
    tags: *id002
    token: 7xZx_gR6goLB_xoHUsMU
doc.publisher:
  172.16.0119:
    id: 25
    tags:
    - doc.publisher
    token: A-_GyswPsuRzneDyw1Lv
docker:
  172.16.192.169:
    id: 17
    tags: &id003
    - docker-executor
    token: ML_X1iZUqQDT5ET5sfcr
  172.16.192.241:
    id: 18
    tags: *id003
    token: brX7TsKxyqC3sYbC_Vdz
msbuilder:
  172.16.19.238:
    id: 21
    tags: &id004
    - builder
    - vs2019
    token: NL7r-jiqJLkds6SsbPWo
  172.16.19.240:
    id: 22
    tags: *id004
    token: _SVzJq22daZZTvZf8C5m
